package com.untill.driver.interfaces.eft;

/**
 * Gift Card Activation request. Driver responds with {@link EftResult} or throws RuntimeException. 
 * Depending on unTill(r) POS action settings, cardId may be provided or not. 
 * Two scenarios are possible regarding cardId argument in this request (configurable at POS side):
 * <ul>
 * <li>cardId typed/scanned by unTill(r) POS - then it will be non-empty in request</li>
 * <li>cardId is obtained/generated by driver - then it will be empty in request</li>
 * </ul>
 * @see IEft 
 *
 */
public class EftGiftCardActivateRequest extends EftGiftCardValueTransactionRequest {
	@Override
	public String toString() {
		return "EftGiftCardActivateRequest{} " + super.toString();
	}
}
